# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

assign_datapoints <- function(data, centroids) {
    .Call(`_HiTMapper_assign_datapoints`, data, centroids)
}

compute_centroids <- function(data, mapping, k) {
    .Call(`_HiTMapper_compute_centroids`, data, mapping, k)
}

clustering_main <- function(data, cova, grid_size, total_nodes, min_node_size, n_passes) {
    .Call(`_HiTMapper_clustering_main`, data, cova, grid_size, total_nodes, min_node_size, n_passes)
}

