# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_datapoints <- function(data, centroids) {
    .Call(`_HiTMapper_predict_datapoints`, data, centroids)
}

get_edgelist <- function(idx) {
    .Call(`_HiTMapper_get_edgelist`, idx)
}

sample_cells <- function(mapping, uniq, m) {
    .Call(`_HiTMapper_sample_cells`, mapping, uniq, m)
}

compute_centroids <- function(data, mapping, k) {
    .Call(`_HiTMapper_compute_centroids`, data, mapping, k)
}

clustering_main <- function(data, cova, grid_size, total_nodes, min_node_size, n_passes) {
    .Call(`_HiTMapper_clustering_main`, data, cova, grid_size, total_nodes, min_node_size, n_passes)
}

