# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

intersections <- function(nodes) {
    .Call(`_HiTMapper_intersections`, nodes)
}

som <- function(data, nx, ny, C = 10L, lr = 0.2) {
    .Call(`_HiTMapper_som`, data, nx, ny, C, lr)
}

